#!/usr/bin/env bash

# source colors
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${dir}/colorizer-lib/colorizer.sh"

if [ "$UID" -ne 0 ]; then
  colorize "<red>Please run as root</red>"
  exit 1
fi

cd /apps

apps=( node python ruby go ghost )

# loop through langs
# build
for app in "${apps[@]}"
do
    app_conf=$(cat ${dir}/apps.json | jq .[] | jq 'select(.subdomain == "'${app}'")')
    lang=$(echo ${app_conf} | jq --raw-output '.lang')
    image_name=${lang}/base
    if docker images | awk '{ print $1 }' | grep "^${image_name}$" > /dev/null; then
        colorize "<red>${IMAGE_NAME} was already built!</red>"
    else
        colorize "<cyan>building ${lang}...</cyan>"
        docker build --rm -t  ${lang}/base ${app}/
    fi
done

# clean up
/scripts/clean-docker

colorize "<white>Done!!</white>"