#!/usr/bin/env bash

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "${dir}/colorizer-lib/colorizer.sh"

function setup_nginx(){
    # source colors
    if [ "$UID" -ne 0 ]; then
        colorize "<red>Please run as root</red>"
        exit 1
    fi

    rm -rf /etc/nginx
    mkdir /etc/nginx
    cp -r /var/presentation/nginx/* /etc/nginx/

    # restart nginx
    service nginx restart

    colorize "<purple>nginx</purple> <white>is now setup!!</white>"
}

setup_nginx